# Generated by Django 3.1.7 on 2021-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='gender',
            field=models.CharField(default=1, max_length=50, verbose_name='genero'),
            preserve_default=False,
        ),
    ]
