# Generated by Django 3.1.7 on 2021-04-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_empleado_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='gender',
        ),
    ]
